stages:
  - build
  - test
  - docker_build
  - release
  - deploy

build:
  stage: build
  image: python:3.10
  script:
    - pip install -r requirements.txt
    - echo "Build complete"

test:
  stage: test
  image: python:3.10 # بيستخدم صورة Python الرسمية لتشغيل الاختبارات
  variables:
    PYTHONPATH: "$CI_PROJECT_DIR" # بيضيف مجلد المشروع لمسار Python (مفيد لو عندك import داخلي)
  script:
    - pip install -r requirements.txt # تثبيت مكتبات المشروع
    - python -m unittest discover -s tests -p "test_*.py" # اكتشاف وتشغيل كل ملفات الاختبار داخل مجلد tests

docker_build:
  stage: docker_build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

release:
  stage: release
  image: alpine:latest
  script:
    - >
      echo "Release created: v1.0.${CI_PIPELINE_IID}"
    - >
      echo "Release info: image=${CI_REGISTRY_IMAGE}:latest"
  only:
    - main

deploy:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest
    - docker run -d -p 5000:5000 $CI_REGISTRY_IMAGE:latest
    - echo "Deployed image to container"
  only:
    - main